-- Utilizando o UPDATE para atualizar os valores

SELECT NOME, EMAIL
FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'LILIAN@HOTMAIL.COM'

SELECT NOME, EMAIL
FROM CLIENTE;

SELECT * FROM CLIENTE
WHERE NOME = 'LILIAN';

SELECT * FROM CLIENTE
WHERE NOME = 'JOAO';

UPDATE CLIENTE
SET EMAIL = 'JOAO@IG.COM.BR'
WHERE NOME = 'JOAO';

SELECT NOME, EMAIL
FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'JORGE@IG.COM.BR'
WHERE NOME = 'JORGE';

SELECT NOME, EMAIL
FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'CELTA@HOTMAIL.COM.BR'
WHERE NOME = 'CELTA';

SELECT NOME, EMAIL
FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'ANA@HOTMAIL.COM.BR'
WHERE NOME = 'ANA';

SELECT NOME, EMAIL
FROM CLIENTE;

UPDATE CLIENTE
SET EMAIL = 'CARLA@IG.COM.BR'
WHERE NOME = 'CARLA';

SELECT NOME, EMAIL
FROM CLIENTE;
