/*
Aula 23 - Tabela Verdade
Operadores Lógicos AND e OR
Curso Udemy: O curso completo de Banco de Dados e SQL, sem mistérios!
Professor: Felipe Mafra
*/

-- Operadores Lógicos

-- OR == OU

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE
SEXO = 'M' OR ENDERECO LIKE '%RJ';

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE
SEXO = 'F' OR ENDERECO LIKE '%ESTACIO';

-- AND == E

SELECT NOME, SEXO ENDERECO FROM CLIENTE
WHERE
SEXO = 'M' AND ENDERECO LIKE '%RJ'

SELECT NOME, SEXO, ENDERECO FROM CLIENTE
WHERE
SEXO = 'F' AND ENDERECO LIKE '%ESTACIO'
